import { useFieldFlow } from "@/lib/store";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Bell, Mail, MessageSquare, Smartphone, Terminal, CheckCircle2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";

const channelIcons = {
  Email: Mail,
  SMS: Smartphone,
  WhatsApp: MessageSquare,
  DevLog: Terminal,
};

const channelColors = {
  Email: "bg-blue-50 text-blue-700 border-blue-200",
  SMS: "bg-amber-50 text-amber-700 border-amber-200",
  WhatsApp: "bg-emerald-50 text-emerald-700 border-emerald-200",
  DevLog: "bg-purple-50 text-purple-700 border-purple-200",
};

export function NotificationsDrawer({
  open,
  onOpenChange,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const { notificationLogs } = useFieldFlow();

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent className="w-full sm:max-w-md p-0 flex flex-col bg-card">
        <SheetHeader className="p-6 border-b border-hairline">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="size-8 rounded-lg bg-primary/10 text-primary grid place-items-center">
                <Bell className="size-4" />
              </div>
              <SheetTitle className="text-base font-semibold">Notifications</SheetTitle>
            </div>
            <Badge variant="outline" className="text-xs font-mono">
              {notificationLogs.length} events
            </Badge>
          </div>
          <SheetDescription className="text-xs text-muted-foreground mt-1">
            Example updates generated by ticket activity. Messages are simulated in this demo.
          </SheetDescription>
        </SheetHeader>

        <div className="flex-1 overflow-y-auto p-4 space-y-3">
          {notificationLogs.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground text-sm">
              No updates yet. Ticket activity will appear here.
            </div>
          ) : (
            notificationLogs.map((log) => {
              const Icon = channelIcons[log.channel] || Terminal;
              return (
                <div
                  key={log.id}
                  className="rounded-xl border border-hairline bg-surface p-3.5 space-y-2 text-xs transition-colors hover:border-border"
                >
                  <div className="flex items-center justify-between gap-2">
                    <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full border text-[10px] font-medium ${channelColors[log.channel]}`}>
                      <Icon className="size-3" />
                      {log.channel}
                    </span>
                    <span className="text-[11px] text-muted-foreground font-mono">{log.sentAt}</span>
                  </div>

                  <div className="font-medium text-foreground text-[13px] flex items-center justify-between">
                    <span>{log.triggerEvent}</span>
                    <span className="font-mono text-muted-foreground text-[11px]">{log.ticketId}</span>
                  </div>

                  <p className="text-muted-foreground leading-relaxed bg-elevated p-2 rounded-lg border border-hairline font-mono text-[11px]">
                    {log.messagePreview}
                  </p>

                  <div className="flex items-center justify-between text-[11px] text-muted-foreground pt-1 border-t border-hairline/60">
                    <span className="truncate max-w-[200px]">To: <strong>{log.recipient}</strong></span>
                    <span className="inline-flex items-center gap-1 text-emerald-600 font-medium">
                      <CheckCircle2 className="size-3" />
                      {log.status}
                    </span>
                  </div>
                </div>
              );
            })
          )}
        </div>
      </SheetContent>
    </Sheet>
  );
}

