/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomerIndexRouteImport } from './routes/customer/index'
import { Route as TechIndexRouteImport } from './routes/tech/index'
import { Route as TechJobIdRouteImport } from './routes/tech/$jobId'
import { Route as TechniciansIndexRouteImport } from './routes/technicians/index'
import { Route as TicketsIndexRouteImport } from './routes/tickets/index'
import { Route as TicketsTicketIdRouteImport } from './routes/tickets/$ticketId'
import { Route as TrackTicketIdRouteImport } from './routes/track/$ticketId'
import { Route as ApiV1BootstrapRouteImport } from './routes/api/v1/bootstrap'
import { Route as ApiV1DashboardMetricsRouteImport } from './routes/api/v1/dashboard/metrics'
import { Route as ApiV1TicketsIndexRouteImport } from './routes/api/v1/tickets/index'
import { Route as ApiV1CustomersIdTicketsRouteImport } from './routes/api/v1/customers/$id/tickets'
import { Route as ApiV1TechniciansIdJobsRouteImport } from './routes/api/v1/technicians/$id/jobs'
import { Route as ApiV1TicketsIdIndexRouteImport } from './routes/api/v1/tickets/$id/index'
import { Route as ApiV1TicketsIdAssignRouteImport } from './routes/api/v1/tickets/$id/assign'
import { Route as ApiV1TicketsIdAttachmentsRouteImport } from './routes/api/v1/tickets/$id/attachments'
import { Route as ApiV1TicketsIdCommentsRouteImport } from './routes/api/v1/tickets/$id/comments'
import { Route as ApiV1TicketsIdHistoryRouteImport } from './routes/api/v1/tickets/$id/history'
import { Route as ApiV1TicketsIdStatusRouteImport } from './routes/api/v1/tickets/$id/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/customer/',
  path: '/customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechIndexRoute = TechIndexRouteImport.update({
  id: '/tech/',
  path: '/tech/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechJobIdRoute = TechJobIdRouteImport.update({
  id: '/tech/$jobId',
  path: '/tech/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniciansIndexRoute = TechniciansIndexRouteImport.update({
  id: '/technicians/',
  path: '/technicians/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsTicketIdRoute = TicketsTicketIdRouteImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTicketIdRoute = TrackTicketIdRouteImport.update({
  id: '/track/$ticketId',
  path: '/track/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1BootstrapRoute = ApiV1BootstrapRouteImport.update({
  id: '/api/v1/bootstrap',
  path: '/api/v1/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DashboardMetricsRoute = ApiV1DashboardMetricsRouteImport.update({
  id: '/api/v1/dashboard/metrics',
  path: '/api/v1/dashboard/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TicketsIndexRoute = ApiV1TicketsIndexRouteImport.update({
  id: '/api/v1/tickets/',
  path: '/api/v1/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CustomersIdTicketsRoute = ApiV1CustomersIdTicketsRouteImport.update({
  id: '/api/v1/customers/$id/tickets',
  path: '/api/v1/customers/$id/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TechniciansIdJobsRoute = ApiV1TechniciansIdJobsRouteImport.update({
  id: '/api/v1/technicians/$id/jobs',
  path: '/api/v1/technicians/$id/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TicketsIdIndexRoute = ApiV1TicketsIdIndexRouteImport.update({
  id: '/api/v1/tickets/$id/',
  path: '/api/v1/tickets/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TicketsIdAssignRoute = ApiV1TicketsIdAssignRouteImport.update({
  id: '/api/v1/tickets/$id/assign',
  path: '/api/v1/tickets/$id/assign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TicketsIdAttachmentsRoute =
  ApiV1TicketsIdAttachmentsRouteImport.update({
    id: '/api/v1/tickets/$id/attachments',
    path: '/api/v1/tickets/$id/attachments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1TicketsIdCommentsRoute = ApiV1TicketsIdCommentsRouteImport.update({
  id: '/api/v1/tickets/$id/comments',
  path: '/api/v1/tickets/$id/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TicketsIdHistoryRoute = ApiV1TicketsIdHistoryRouteImport.update({
  id: '/api/v1/tickets/$id/history',
  path: '/api/v1/tickets/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TicketsIdStatusRoute = ApiV1TicketsIdStatusRouteImport.update({
  id: '/api/v1/tickets/$id/status',
  path: '/api/v1/tickets/$id/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/tech/$jobId': typeof TechJobIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/track/$ticketId': typeof TrackTicketIdRoute
  '/customer/': typeof CustomerIndexRoute
  '/tech/': typeof TechIndexRoute
  '/technicians/': typeof TechniciansIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/api/v1/bootstrap': typeof ApiV1BootstrapRoute
  '/api/v1/dashboard/metrics': typeof ApiV1DashboardMetricsRoute
  '/api/v1/tickets/': typeof ApiV1TicketsIndexRoute
  '/api/v1/customers/$id/tickets': typeof ApiV1CustomersIdTicketsRoute
  '/api/v1/technicians/$id/jobs': typeof ApiV1TechniciansIdJobsRoute
  '/api/v1/tickets/$id/assign': typeof ApiV1TicketsIdAssignRoute
  '/api/v1/tickets/$id/attachments': typeof ApiV1TicketsIdAttachmentsRoute
  '/api/v1/tickets/$id/comments': typeof ApiV1TicketsIdCommentsRoute
  '/api/v1/tickets/$id/history': typeof ApiV1TicketsIdHistoryRoute
  '/api/v1/tickets/$id/status': typeof ApiV1TicketsIdStatusRoute
  '/api/v1/tickets/$id/': typeof ApiV1TicketsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/tech/$jobId': typeof TechJobIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/track/$ticketId': typeof TrackTicketIdRoute
  '/customer': typeof CustomerIndexRoute
  '/tech': typeof TechIndexRoute
  '/technicians': typeof TechniciansIndexRoute
  '/tickets': typeof TicketsIndexRoute
  '/api/v1/bootstrap': typeof ApiV1BootstrapRoute
  '/api/v1/dashboard/metrics': typeof ApiV1DashboardMetricsRoute
  '/api/v1/tickets': typeof ApiV1TicketsIndexRoute
  '/api/v1/customers/$id/tickets': typeof ApiV1CustomersIdTicketsRoute
  '/api/v1/technicians/$id/jobs': typeof ApiV1TechniciansIdJobsRoute
  '/api/v1/tickets/$id/assign': typeof ApiV1TicketsIdAssignRoute
  '/api/v1/tickets/$id/attachments': typeof ApiV1TicketsIdAttachmentsRoute
  '/api/v1/tickets/$id/comments': typeof ApiV1TicketsIdCommentsRoute
  '/api/v1/tickets/$id/history': typeof ApiV1TicketsIdHistoryRoute
  '/api/v1/tickets/$id/status': typeof ApiV1TicketsIdStatusRoute
  '/api/v1/tickets/$id': typeof ApiV1TicketsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/tech/$jobId': typeof TechJobIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/track/$ticketId': typeof TrackTicketIdRoute
  '/customer/': typeof CustomerIndexRoute
  '/tech/': typeof TechIndexRoute
  '/technicians/': typeof TechniciansIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/api/v1/bootstrap': typeof ApiV1BootstrapRoute
  '/api/v1/dashboard/metrics': typeof ApiV1DashboardMetricsRoute
  '/api/v1/tickets/': typeof ApiV1TicketsIndexRoute
  '/api/v1/customers/$id/tickets': typeof ApiV1CustomersIdTicketsRoute
  '/api/v1/technicians/$id/jobs': typeof ApiV1TechniciansIdJobsRoute
  '/api/v1/tickets/$id/assign': typeof ApiV1TicketsIdAssignRoute
  '/api/v1/tickets/$id/attachments': typeof ApiV1TicketsIdAttachmentsRoute
  '/api/v1/tickets/$id/comments': typeof ApiV1TicketsIdCommentsRoute
  '/api/v1/tickets/$id/history': typeof ApiV1TicketsIdHistoryRoute
  '/api/v1/tickets/$id/status': typeof ApiV1TicketsIdStatusRoute
  '/api/v1/tickets/$id/': typeof ApiV1TicketsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/tech/$jobId'
    | '/tickets/$ticketId'
    | '/track/$ticketId'
    | '/customer/'
    | '/tech/'
    | '/technicians/'
    | '/tickets/'
    | '/api/v1/bootstrap'
    | '/api/v1/dashboard/metrics'
    | '/api/v1/tickets/'
    | '/api/v1/customers/$id/tickets'
    | '/api/v1/technicians/$id/jobs'
    | '/api/v1/tickets/$id/assign'
    | '/api/v1/tickets/$id/attachments'
    | '/api/v1/tickets/$id/comments'
    | '/api/v1/tickets/$id/history'
    | '/api/v1/tickets/$id/status'
    | '/api/v1/tickets/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/tech/$jobId'
    | '/tickets/$ticketId'
    | '/track/$ticketId'
    | '/customer'
    | '/tech'
    | '/technicians'
    | '/tickets'
    | '/api/v1/bootstrap'
    | '/api/v1/dashboard/metrics'
    | '/api/v1/tickets'
    | '/api/v1/customers/$id/tickets'
    | '/api/v1/technicians/$id/jobs'
    | '/api/v1/tickets/$id/assign'
    | '/api/v1/tickets/$id/attachments'
    | '/api/v1/tickets/$id/comments'
    | '/api/v1/tickets/$id/history'
    | '/api/v1/tickets/$id/status'
    | '/api/v1/tickets/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/tech/$jobId'
    | '/tickets/$ticketId'
    | '/track/$ticketId'
    | '/customer/'
    | '/tech/'
    | '/technicians/'
    | '/tickets/'
    | '/api/v1/bootstrap'
    | '/api/v1/dashboard/metrics'
    | '/api/v1/tickets/'
    | '/api/v1/customers/$id/tickets'
    | '/api/v1/technicians/$id/jobs'
    | '/api/v1/tickets/$id/assign'
    | '/api/v1/tickets/$id/attachments'
    | '/api/v1/tickets/$id/comments'
    | '/api/v1/tickets/$id/history'
    | '/api/v1/tickets/$id/status'
    | '/api/v1/tickets/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  TechJobIdRoute: typeof TechJobIdRoute
  TicketsTicketIdRoute: typeof TicketsTicketIdRoute
  TrackTicketIdRoute: typeof TrackTicketIdRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  TechIndexRoute: typeof TechIndexRoute
  TechniciansIndexRoute: typeof TechniciansIndexRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
  ApiV1BootstrapRoute: typeof ApiV1BootstrapRoute
  ApiV1DashboardMetricsRoute: typeof ApiV1DashboardMetricsRoute
  ApiV1TicketsIndexRoute: typeof ApiV1TicketsIndexRoute
  ApiV1CustomersIdTicketsRoute: typeof ApiV1CustomersIdTicketsRoute
  ApiV1TechniciansIdJobsRoute: typeof ApiV1TechniciansIdJobsRoute
  ApiV1TicketsIdAssignRoute: typeof ApiV1TicketsIdAssignRoute
  ApiV1TicketsIdAttachmentsRoute: typeof ApiV1TicketsIdAttachmentsRoute
  ApiV1TicketsIdCommentsRoute: typeof ApiV1TicketsIdCommentsRoute
  ApiV1TicketsIdHistoryRoute: typeof ApiV1TicketsIdHistoryRoute
  ApiV1TicketsIdStatusRoute: typeof ApiV1TicketsIdStatusRoute
  ApiV1TicketsIdIndexRoute: typeof ApiV1TicketsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/customer'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/': {
      id: '/tech/'
      path: '/tech'
      fullPath: '/tech/'
      preLoaderRoute: typeof TechIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/$jobId': {
      id: '/tech/$jobId'
      path: '/tech/$jobId'
      fullPath: '/tech/$jobId'
      preLoaderRoute: typeof TechJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technicians/': {
      id: '/technicians/'
      path: '/technicians'
      fullPath: '/technicians/'
      preLoaderRoute: typeof TechniciansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$ticketId': {
      id: '/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof TicketsTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$ticketId': {
      id: '/track/$ticketId'
      path: '/track/$ticketId'
      fullPath: '/track/$ticketId'
      preLoaderRoute: typeof TrackTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/bootstrap': {
      id: '/api/v1/bootstrap'
      path: '/api/v1/bootstrap'
      fullPath: '/api/v1/bootstrap'
      preLoaderRoute: typeof ApiV1BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/dashboard/metrics': {
      id: '/api/v1/dashboard/metrics'
      path: '/api/v1/dashboard/metrics'
      fullPath: '/api/v1/dashboard/metrics'
      preLoaderRoute: typeof ApiV1DashboardMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tickets/': {
      id: '/api/v1/tickets/'
      path: '/api/v1/tickets'
      fullPath: '/api/v1/tickets/'
      preLoaderRoute: typeof ApiV1TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/customers/$id/tickets': {
      id: '/api/v1/customers/$id/tickets'
      path: '/api/v1/customers/$id/tickets'
      fullPath: '/api/v1/customers/$id/tickets'
      preLoaderRoute: typeof ApiV1CustomersIdTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/technicians/$id/jobs': {
      id: '/api/v1/technicians/$id/jobs'
      path: '/api/v1/technicians/$id/jobs'
      fullPath: '/api/v1/technicians/$id/jobs'
      preLoaderRoute: typeof ApiV1TechniciansIdJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tickets/$id/': {
      id: '/api/v1/tickets/$id/'
      path: '/api/v1/tickets/$id'
      fullPath: '/api/v1/tickets/$id/'
      preLoaderRoute: typeof ApiV1TicketsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tickets/$id/assign': {
      id: '/api/v1/tickets/$id/assign'
      path: '/api/v1/tickets/$id/assign'
      fullPath: '/api/v1/tickets/$id/assign'
      preLoaderRoute: typeof ApiV1TicketsIdAssignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tickets/$id/attachments': {
      id: '/api/v1/tickets/$id/attachments'
      path: '/api/v1/tickets/$id/attachments'
      fullPath: '/api/v1/tickets/$id/attachments'
      preLoaderRoute: typeof ApiV1TicketsIdAttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tickets/$id/comments': {
      id: '/api/v1/tickets/$id/comments'
      path: '/api/v1/tickets/$id/comments'
      fullPath: '/api/v1/tickets/$id/comments'
      preLoaderRoute: typeof ApiV1TicketsIdCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tickets/$id/history': {
      id: '/api/v1/tickets/$id/history'
      path: '/api/v1/tickets/$id/history'
      fullPath: '/api/v1/tickets/$id/history'
      preLoaderRoute: typeof ApiV1TicketsIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/tickets/$id/status': {
      id: '/api/v1/tickets/$id/status'
      path: '/api/v1/tickets/$id/status'
      fullPath: '/api/v1/tickets/$id/status'
      preLoaderRoute: typeof ApiV1TicketsIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  TechJobIdRoute: TechJobIdRoute,
  TicketsTicketIdRoute: TicketsTicketIdRoute,
  TrackTicketIdRoute: TrackTicketIdRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  TechIndexRoute: TechIndexRoute,
  TechniciansIndexRoute: TechniciansIndexRoute,
  TicketsIndexRoute: TicketsIndexRoute,
  ApiV1BootstrapRoute: ApiV1BootstrapRoute,
  ApiV1DashboardMetricsRoute: ApiV1DashboardMetricsRoute,
  ApiV1TicketsIndexRoute: ApiV1TicketsIndexRoute,
  ApiV1CustomersIdTicketsRoute: ApiV1CustomersIdTicketsRoute,
  ApiV1TechniciansIdJobsRoute: ApiV1TechniciansIdJobsRoute,
  ApiV1TicketsIdAssignRoute: ApiV1TicketsIdAssignRoute,
  ApiV1TicketsIdAttachmentsRoute: ApiV1TicketsIdAttachmentsRoute,
  ApiV1TicketsIdCommentsRoute: ApiV1TicketsIdCommentsRoute,
  ApiV1TicketsIdHistoryRoute: ApiV1TicketsIdHistoryRoute,
  ApiV1TicketsIdStatusRoute: ApiV1TicketsIdStatusRoute,
  ApiV1TicketsIdIndexRoute: ApiV1TicketsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
