/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomerIndexRouteImport } from './routes/customer/index'
import { Route as TechIndexRouteImport } from './routes/tech/index'
import { Route as TechJobIdRouteImport } from './routes/tech/$jobId'
import { Route as TechniciansIndexRouteImport } from './routes/technicians/index'
import { Route as TicketsIndexRouteImport } from './routes/tickets/index'
import { Route as TicketsTicketIdRouteImport } from './routes/tickets/$ticketId'
import { Route as TrackTicketIdRouteImport } from './routes/track/$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/customer/',
  path: '/customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechIndexRoute = TechIndexRouteImport.update({
  id: '/tech/',
  path: '/tech/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechJobIdRoute = TechJobIdRouteImport.update({
  id: '/tech/$jobId',
  path: '/tech/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniciansIndexRoute = TechniciansIndexRouteImport.update({
  id: '/technicians/',
  path: '/technicians/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsTicketIdRoute = TicketsTicketIdRouteImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTicketIdRoute = TrackTicketIdRouteImport.update({
  id: '/track/$ticketId',
  path: '/track/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/tech/$jobId': typeof TechJobIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/track/$ticketId': typeof TrackTicketIdRoute
  '/customer/': typeof CustomerIndexRoute
  '/tech/': typeof TechIndexRoute
  '/technicians/': typeof TechniciansIndexRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/tech/$jobId': typeof TechJobIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/track/$ticketId': typeof TrackTicketIdRoute
  '/customer': typeof CustomerIndexRoute
  '/tech': typeof TechIndexRoute
  '/technicians': typeof TechniciansIndexRoute
  '/tickets': typeof TicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/tech/$jobId': typeof TechJobIdRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/track/$ticketId': typeof TrackTicketIdRoute
  '/customer/': typeof CustomerIndexRoute
  '/tech/': typeof TechIndexRoute
  '/technicians/': typeof TechniciansIndexRoute
  '/tickets/': typeof TicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/tech/$jobId'
    | '/tickets/$ticketId'
    | '/track/$ticketId'
    | '/customer/'
    | '/tech/'
    | '/technicians/'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/tech/$jobId'
    | '/tickets/$ticketId'
    | '/track/$ticketId'
    | '/customer'
    | '/tech'
    | '/technicians'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/tech/$jobId'
    | '/tickets/$ticketId'
    | '/track/$ticketId'
    | '/customer/'
    | '/tech/'
    | '/technicians/'
    | '/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  TechJobIdRoute: typeof TechJobIdRoute
  TicketsTicketIdRoute: typeof TicketsTicketIdRoute
  TrackTicketIdRoute: typeof TrackTicketIdRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  TechIndexRoute: typeof TechIndexRoute
  TechniciansIndexRoute: typeof TechniciansIndexRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/customer'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/': {
      id: '/tech/'
      path: '/tech'
      fullPath: '/tech/'
      preLoaderRoute: typeof TechIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech/$jobId': {
      id: '/tech/$jobId'
      path: '/tech/$jobId'
      fullPath: '/tech/$jobId'
      preLoaderRoute: typeof TechJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technicians/': {
      id: '/technicians/'
      path: '/technicians'
      fullPath: '/technicians/'
      preLoaderRoute: typeof TechniciansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$ticketId': {
      id: '/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof TicketsTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$ticketId': {
      id: '/track/$ticketId'
      path: '/track/$ticketId'
      fullPath: '/track/$ticketId'
      preLoaderRoute: typeof TrackTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  TechJobIdRoute: TechJobIdRoute,
  TicketsTicketIdRoute: TicketsTicketIdRoute,
  TrackTicketIdRoute: TrackTicketIdRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  TechIndexRoute: TechIndexRoute,
  TechniciansIndexRoute: TechniciansIndexRoute,
  TicketsIndexRoute: TicketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
